---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: tomcat-servers
  require_chef_for_busser: false
  require_ruby_for_busser: true
  require_ansible_repo: true
  ansible_verbose: true
  ansible_version: latest
  extra_vars:
    a: b

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
    attributes:
